name: oscarruizcode_pingu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  video_player: ^2.5.0
  mysql1: ^0.20.0
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/imagenes/fondo.png
   - assets/imagenes/logo.png
   - assets/imagenes/juego.png
   - assets/videos/fondo_inicio.mp4
   - assets/sonidos/musica.mp3
   - assets/personajes/principal/andar/andar1.png
   - assets/personajes/principal/andar/andar2.png
   - assets/personajes/principal/andar/andar3.png
   - assets/personajes/principal/andar/andar4.png
   - assets/personajes/principal/andar/andar5.png
   - assets/personajes/principal/andar/andar6.png
   - assets/personajes/principal/andar/andar7.png
   - assets/personajes/principal/deslizarse/deslizarse1.png
   - assets/personajes/principal/deslizarse/deslizarse2.png
   - assets/personajes/principal/deslizarse/deslizarse3.png
   - assets/personajes/principal/deslizarse/deslizarse4.png
   - assets/personajes/principal/saltar/saltar1.png
   - assets/personajes/principal/saltar/saltar2.png
   - assets/personajes/principal/saltar/saltar3.png
   - assets/personajes/principal/agacharse/agacharse1.png
   - assets/personajes/principal/agacharse/agacharse2.png
   - assets/personajes/principal/agacharse/agacharse3.png
   - assets/personajes/principal/andar_agachado/andar_agachado1.png
   - assets/personajes/principal/andar_agachado/andar_agachado2.png
   - assets/personajes/principal/andar_agachado/andar_agachado3.png
   - assets/personajes/principal/andar_agachado/andar_agachado4.png
   - assets/personajes/principal/andar_agachado/andar_agachado5.png
   - assets/personajes/principal/andar_agachado/andar_agachado6.png
   - assets/personajes/principal/deslizarse_agachado/deslizarse_agachado1.png
   - assets/personajes/principal/deslizarse_agachado/deslizarse_agachado2.png
   - assets/personajes/principal/deslizarse_agachado/deslizarse_agachado3.png
   - assets/personajes/principal/saltar_agachado/saltar_agachado1.png
   - assets/personajes/principal/saltar_agachado/saltar_agachado2.png
   - assets/personajes/items/monedas/monedacoin.png
   - assets/personajes/items/monedas/monedasalto.png
   - assets/personajes/items/monedas/monedavelocidad.png
   - assets/personajes/items/casa/casita.png
   - assets/perfil/gratis/
   - assets/perfil/premium/
   - assets/etiquetas/
   - assets/avatar/defecto.png
   - assets/objetos/suelo/suelo.png
   - assets/objetos/suelo/suelo2.png

  

